### ISSUE TITLE
Will you consider  integrating reactive property?

### ISSUE THREAD

**Issue by singno** [blendle/Hanson#15]
For example:
```
observe(observable) { (e) in
    cb();
}

cb();
````

But with reactive property I can code like this:
```
observable.subscribe { (e) in
    cb();
}
```

**Comment by joostvandijk** [comment]
Hi @singno,

Do you mean that subscribing with a reactive library invokes the given closure immediately on subscribing? Or are you talking about the difference in syntax?

The first is because we felt it was more logical to not invoke the closure immediately, but only after an event is published. Hanson's 'bind' functions do invoke the closure inmesiately.

The different syntax is because ae wanted the instance that madd the observation to own the observation. Therefore, all 'observe' and 'bind' functions are instance methods (they're called on 'self'). That way, the observing instance can keep a reference to its observations, and automatically stop and release them when the observing instance is released.

**Comment by singno** [comment]
I mean the first one.   

I know "bind" invokes immediately, but i don't know how to bind property with method. I want the  observable to be reactive like RxSwift's "behaviour subject" .

Seems the syntax would be like:
```
bind(observable, to: self) {
      controller, value in
      controller.method(value);
}
```

It seems verbose.But anyway, it is an awesome lightweight library.

**Comment by joostvandijk** [comment]
The 'bind' function with a closure was indeed designed to invoke a method like in your example. So that would be the way to do it. However, you can always add an extension with your own 'subscribe' method that behaves the way that best suits you.

Thanks for using Hanson!
